apiVersion: v1
kind: Service
metadata:
  name: loadgenerator-service
spec:
  selector:
    app: loadgenerator
  type: NodePort
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30001